// Copyright (c) 2023 Tencent. All rights reserved.
// Author: felixyyan

namespace trtc {

  public enum TXLiteAVError {
    ERR_NULL = 0,
    ERR_ROOM_ENTER_FAIL = -3301,
    ERR_ENTER_ROOM_PARAM_NULL = -3316,
    ERR_SDK_APPID_INVALID = -3317,
    ERR_ROOM_ID_INVALID = -3318,
    ERR_USER_ID_INVALID = -3319,
    ERR_USER_SIG_INVALID = -3320,
    ERR_ROOM_REQUEST_ENTER_ROOM_TIMEOUT = -3308,
    ERR_SERVER_INFO_SERVICE_SUSPENDED = -100013,
    ERR_ROOM_REQUEST_QUIT_ROOM_TIMEOUT = -3325,
    ERR_CAMERA_START_FAIL = -1301,
    ERR_CAMERA_NOT_AUTHORIZED = -1314,
    ERR_CAMERA_SET_PARAM_FAIL = -1315,
    ERR_CAMERA_OCCUPY = -1316,
    ERR_MIC_START_FAIL = -1302,
    ERR_MIC_NOT_AUTHORIZED = -1317,
    ERR_MIC_SET_PARAM_FAIL = -1318,
    ERR_MIC_OCCUPY = -1319,
    ERR_MIC_STOP_FAIL = -1320,
    ERR_SPEAKER_START_FAIL = -1321,
    ERR_SPEAKER_SET_PARAM_FAIL = -1322,
    ERR_SPEAKER_STOP_FAIL = -1323,
    ERR_VIDEO_ENCODE_FAIL = -1303,
    ERR_UNSUPPORTED_RESOLUTION = -1305,
    ERR_AUDIO_ENCODE_FAIL = -1304,
    ERR_UNSUPPORTED_SAMPLERATE = -1306,
    ERR_PIXEL_FORMAT_UNSUPPORTED = -1327,
    ERR_BUFFER_TYPE_UNSUPPORTED = -1328,
  }

  public enum TXLiteAVWarning {
    WARNING_HW_ENCODER_START_FAIL = 1103,
    WARNING_VIDEO_ENCODER_SW_TO_HW = 1107,
    WARNING_INSUFFICIENT_CAPTURE_FPS = 1108,
    WARNING_SW_ENCODER_START_FAIL = 1109,
    WARNING_REDUCE_CAPTURE_RESOLUTION = 1110,
    WARNING_CAMERA_DEVICE_EMPTY = 1111,
    WARNING_CAMERA_NOT_AUTHORIZED = 1112,
    WARNING_MICROPHONE_DEVICE_EMPTY = 1201,
    WARNING_SPEAKER_DEVICE_EMPTY = 1202,
    WARNING_MICROPHONE_NOT_AUTHORIZED = 1203,
    WARNING_MICROPHONE_DEVICE_ABNORMAL = 1204,
    WARNING_SPEAKER_DEVICE_ABNORMAL = 1205,
    WARNING_VIDEO_FRAME_DECODE_FAIL = 2101,
    WARNING_AUDIO_FRAME_DECODE_FAIL = 2102,
    WARNING_VIDEO_PLAY_LAG = 2105,
    WARNING_HW_DECODER_START_FAIL = 2106,
    WARNING_VIDEO_DECODER_HW_TO_SW = 2108,
    WARNING_SW_DECODER_START_FAIL = 2109,
    WARNING_VIDEO_RENDER_FAIL = 2110,
    WARNING_START_CAPTURE_IGNORED = 4000,
    WARNING_AUDIO_RECORDING_WRITE_FAIL = 7001,
    WARNING_ROOM_DISCONNECT = 5101,
    WARNING_IGNORE_UPSTREAM_FOR_AUDIENCE = 6001,
  }

}
